// <auto-generated />
using AprendaMaisSistema.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AprendaMaisSistema.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AprendaMaisSistema.Models.Alunos", b =>
                {
                    b.Property<int>("AlunosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AlunosId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlunosId"));

                    b.Property<string>("CpfAlunos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CpfAlunos");

                    b.Property<string>("EmailAlunos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmailAlunos");

                    b.Property<string>("FoneAlunos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FoneAlunos");

                    b.Property<string>("NomeAlunos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NomeAlunos");

                    b.Property<string>("SexoAlunos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SexoAlunos");

                    b.HasKey("AlunosId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("AprendaMaisSistema.Models.Materias", b =>
                {
                    b.Property<int>("MateriasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MateriasId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MateriasId"));

                    b.Property<string>("NomeMaterias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NomeMaterias");

                    b.HasKey("MateriasId");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("AprendaMaisSistema.Models.Professores", b =>
                {
                    b.Property<int>("ProfessoresId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProfessoresId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfessoresId"));

                    b.Property<string>("NomeProfessores")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NomeProfessores");

                    b.HasKey("ProfessoresId");

                    b.ToTable("Professores");
                });
#pragma warning restore 612, 618
        }
    }
}
